services:
  sentinel-gateway:
    build:
      context: .
      dockerfile: Dockerfile.sentinel
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ROUTES_JSON={"/api/test":{"TargetURLs":["http://target-backend-1:9001","http://target-backend-2:9002"],"WindowSeconds":10,"MaxRequests":20}}

  target-backend-1:
    image: ghcr.io/anandraj2224/dummy-backend:manual
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=9001

  target-backend-2:
    image: ghcr.io/anandraj2224/dummy-backend:manual
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=9002