services:
  sentinel-gateway:
    build:
      context: .
      dockerfile: Dockerfile.sentinel
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ROUTES_JSON={"/":{"TargetURLs":["http://ui-server:8081"],"WindowSeconds":60,"MaxRequests":1000},"/api/test":{"TargetURLs":["http://target-backend-1:9001","http://target-backend-2:9002"],"WindowSeconds":10,"MaxRequests":20}}

  target-backend-1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=9001

  target-backend-2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=9002

  ui-server:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8081:8081"
