# build stage
FROM golang:1.26-alpine AS BUILDER

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENV CGO_ENABLED=0

RUN go build -o /app/backend ./cmd/protectedServer

# production stage
FROM scratch

COPY --from=BUILDER /app/backend .

CMD [ "./backend" ]
