# build stage
FROM golang:1.26-alpine AS BUILDER

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENV CGO_ENABLED=0

RUN go build -o /app/sentinel ./cmd/sentinel

# production stage
FROM scratch

COPY --from=BUILDER /app/sentinel .

COPY web/ ./web/

CMD [ "./sentinel" ]
