name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Check Formatting
        run: test -z "$(gofmt -l .)"

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Go Test
        run: go test ./...

      - name: Build Sentinel
        run: go build ./cmd/sentinel

      - name: Build Protected Servers
        run: go build ./cmd/protectedServer

      - name: Build UI Server
        run: go build ./cmd/ui

      - name: Validate Compose
        run: docker compose config

      - name: Build Docker Compose Services
        run: docker compose build
