name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Check Formatting
        run: test -z "$(gofmt -l .)"

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Go Test
        run: go test ./...

      - name: Build Sentinel
        run: go build ./cmd/sentinel

      - name: Build Protected Servers
        run: go build ./cmd/protectedServer

      - name: Validate Compose
        run: docker compose config

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Sentinel
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.sentinel
          push: true
          tags: ghcr.io/anandraj2224/sentinel:${{ github.sha }}
